$(function(){
    $("#neon-button").toggle();
    $("#neon-button").fadeIn(5);
    $("#neon-button").fadeOut(50);
    $("#neon-button").fadeIn(10);
    $("#neon-button").fadeOut(100);
    $("#neon-button").fadeIn(50);
    $("#neon-button").fadeOut(250);
    $("#neon-button").fadeIn(1000);
})